# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='nombre')),
                ('mark', models.CharField(max_length=45, verbose_name='marca')),
                ('price', models.PositiveIntegerField(verbose_name='precio')),
                ('provider', models.CharField(max_length=45, verbose_name='proveedor')),
                ('image', models.ImageField(default='pict_folder/None/no-img.jpg', upload_to='pict_folder/', verbose_name='imagen')),
            ],
        ),
    ]
