# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 05:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20161122_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/None/No-img.jpg', upload_to='media/', verbose_name='imagen'),
        ),
    ]
